### ISSUE TITLE
Conditional selection without generic base interface

### ISSUE THREAD

**Issue by esseb** [FormidableLabs/groqd#159]
The documentation on [Conditional selections with `.grab`](https://formidable.com/open-source/groqd/query-building#conditional-selections-with-grab) results in this interface:

```ts
type QueryResult = (
  | { _id: string; name: "Bulbasaur"; hp: number }
  | { _id: string; name: "Charmander"; attack: number }
  | { _id: string }
)[];
```

However, I want to end up with this interface, without a generic `{ _type: string }` base interface:
```ts
type QueryResult = (
  | { _type: "bulbasaur"; name: string; hp: number }
  | { _type: "charmander"; string; name: string; attack: number }
)[];
```

Using a query something like this (example code, this doesn't work):
```ts
q("*")
  .filter("_type == 'bulbasaur' || _type == 'charmander'")
  .grab(
    {}, // Empty object because I need something here
    {
      "_type == 'bulbasaur'": {
        _type: q.literal("bulbasaur"),
        name: q.string(),
        hp: ["base.HP", q.number()],
      },
      "_type == 'charmander'": {
        _type: q.literal("charmander"),
        name: q.string(,
        attack: ["base.Attack", q.number()],
      },
    }
  );
```

Is there a way to perform a query in GROQD and end up with a union interface containing only the types I requested? Is there something more appropriate than conditional selections I should be using instead?

**Comment by gksander** [comment]
Great question! This is fundamentally a short-coming of `.grab`, but @littlemilkstudio recently added/documented a new [`.select`](https://formidable.com/open-source/groqd/query-building#fork-a-selection-based-on-a-_type) method that should resolve this! In cases like this, I believe you can swap out the `.grab` with two arguments, for a `.select` with just a single argument, and won't have to worry about the pesky empty interface.

If that doesn't resolve this problem for you, let's reopen this issue and discuss further!

**Comment by esseb** [comment]
It feels a little cleaner to use `select` here, but I still have a similar issue. If I drop the `default` I end up with a type similar to this:

```
type QueryResult = (
  | { _type: "bulbasaur"; name: string; hp: number }
  | { _type: "charmander"; string; name: string; attack: number }
  | Record<string, never>
)[];
```

If I do include `default`, e.g. `default: { _type: q.literal("unsupported") }`, I end up with a type similar to this:

```
type QueryResult = (
  | { _type: "bulbasaur"; name: string; hp: number }
  | { _type: "charmander"; string; name: string; attack: number }
  | { _type: "unsupported" }
)[];
```

It is a little clearer at least. Not sure how to improve this. Thanks for looking into this.

**Comment by esseb** [comment]
Very clever. Using default like that makes a lot of sense. This solves my issue, thanks!

Thanks for the tip on the GROQ tool also.
